// <auto-generated />
using ContactListo.DataAccess;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace ContactListo.DataAccess.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20250421134928_InisialApplication")]
    partial class InisialApplication
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("ContactListo.Domain.Contact", b =>
                {
                    b.Property<int>("ContactId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ContactId"));

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Notes")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ContactId");

                    b.ToTable("Contacts");

                    b.HasData(
                        new
                        {
                            ContactId = 1,
                            Address = "Alexandria",
                            FullName = "Mahmoud Samy",
                            PhoneNumber = "01024236263"
                        },
                        new
                        {
                            ContactId = 2,
                            Address = "Cairo",
                            FullName = "Ahmed Ali",
                            PhoneNumber = "01100000000"
                        },
                        new
                        {
                            ContactId = 3,
                            Address = "Cairo",
                            FullName = "Hazem Ahmed",
                            PhoneNumber = "01200000000"
                        },
                        new
                        {
                            ContactId = 4,
                            Address = "Cairo",
                            FullName = "Omar Marzok",
                            PhoneNumber = "01500000000"
                        },
                        new
                        {
                            ContactId = 5,
                            Address = "Cairo",
                            FullName = "Reda Tantawey",
                            PhoneNumber = "01000000000"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
